#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=12:00:00 # walltime
#SBATCH --ntasks=1 # number of processor cores (i.e. tasks)
#SBATCH --nodes=1 # number of nodes
#SBATCH --mem-per-cpu=12000M # memory per CPU core
#SBATCH -J "EP_Proc" # job name
#SBATCH --mail-type=NONE
#SBATCH --output=/fslhome/awheel28/compute/Slurm_Output/slurm_%j.out

# Compatibility variables for PBS. Delete if not needed.
export PBS_NODEFILE='/fslapps/fslutils/generate_pbs_nodefile'
export PBS_JOBID=$SLURM_JOB_ID
export PBS_O_WORKDIR-"$SLURM_SUBMIT_DIR"
export PBS_QUEUE=batch

# Set the max number of threads to use for programs using OpenMP.
# Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
OUTFILE=""

#load Matlab
module load matlab

#submit a single file to the scheduler
matlab -nodisplay -nosplash -r "artifactCorrect_single_sbin('${1}')"

exit 0
