#!/bin/sh
#
#SBATCH -J "QueueProc" # job name
#
#SBATCH --ntasks=1
#SBATCH --time=2-00:00:00
#SBATCH --mem-per-cpu=100
#SBATCH --mail-user=awheel28@byu.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/fslhome/awheel28/compute/Slurm_Output/master_submit_%j.txt

#Process all of the files found in the specified directory
#Will loop through and submit a job for each file found
for FILE in /fslhome/awheel28/~compute/ENTERPATH/*.sbin; do

  #print path and filename
  echo ${FILE}

  y=${FILE%.sbin}
  fname=${y##*/}

  echo ${fname}

  #submit the bash script to process file
  sbatch --output=/fslhome/awheel28/~compute/Slurm_Output/${fname}.txt\
   pbsSubmitSingFile_sbin ${FILE}

  sleep 2 #be nice to the scheduler

done

exit 0
